#install.packages("twitteR")
#install.packages("rtweet")
#devtools::install_github("mkearney/rtweet", ref = "79fdf4aa7d219793bf2b201ce059f3bd6395bc7b")

library(twitteR)
library(readr)
library(tidyverse)
#install.packages("datapasta")

### Llaves de acceso a API Twitter
consumerKey = 'xeKkhl9LnbgHJbkhcFYxFnOhg'
consumerSecret = '7T1IwCH8pFuhyszaqvVPnTanuqtPJaE00IAkIrAJtqTYjwuRvZ'
accessToken = '1214735980172845056-SYK0B3E7bJPoHj5b4kjIRShNoskiCZ'
accessTokenSecret = 'URJX6yeIIY3r0c9C9HfzYWD3GqPeOn46VVooAmv2Ool5P'

setup_twitter_oauth(consumer_key = consumerKey, 
                    consumer_secret = consumerSecret, 
                    access_token = accessToken, 
                    access_secret = accessTokenSecret)

#base_atajo <- readxl::read_excel("base/Atajos.xlsx", sheet = "Hoja1", col_names = TRUE)

base_atajo <- data.frame(stringsAsFactors=FALSE,
   Description_eng = c("Move cursor to Console", "Clear console",
                       "Move cursor to beginning of line",
                       "Move cursor to end of line", "Navigate command history",
                       "Popup command history", "Interrupt currently executing command",
                       "Change working directory", "Go to File/Function",
                       "Move cursor to Source Editor", "New document (except on Chrome/Windows)",
                       "New document (Chrome only)", "Open document",
                       "Save active document", "Close active document (except on Chrome)",
                       "Close active document (Chrome only)",
                       "Close all open documents", "Preview HTML (Markdown and HTML)",
                       "Knit Document (knitr)", "Compile Notebook",
                       "Compile PDF (TeX and Sweave)", "Insert chunk (Sweave and Knitr)",
                       "Insert code section", "Run current line/selection",
                       "Run current line/selection (retain cursor position)", "Re-run previous region",
                       "Run current document",
                       "Run from document beginning to current line", "Run from current line to document end",
                       "Run the current function definition",
                       "Run the current code section", "Run previous Sweave/Rmd code",
                       "Run the current Sweave/Rmd chunk", "Run the next Sweave/Rmd chunk",
                       "Source a file", "Source the current document",
                       "Source the current document (with echo)", "Fold Selected",
                       "Unfold Selected", "Fold All", "Unfold All", "Go to line", "Jump to",
                       "Switch to tab", "Previous tab", "Next tab", "First tab",
                       "Last tab", "Navigate back", "Navigate forward",
                       "Extract function from selection", "Extract variable from selection",
                       "Reindent lines",
                       "Comment/uncomment current line/selection", "Reflow Comment", "Reformat Selection",
                       "Show Diagnostics", "Transpose Letters", "Move Lines Up/Down",
                       "Copy Lines Up/Down", "Jump to Matching Brace/Paren",
                       "Expand to Matching Brace/Paren", "Select to Matching Brace/Paren",
                       "Add Cursor Above Current Cursor",
                       "Add Cursor Below Current Cursor", "Move Active Cursor Up",
                       "Move Active Cursor Down", "Find and Replace", "Find Next", "Find Previous",
                       "Use Selection for Find", "Replace and Find", "Find in Files",
                       "Check Spelling", "Undo", "Redo", "Cut", "Copy", "Paste",
                       "Select All", "Jump to Word", "Jump to Start/End",
                       "Delete Line", "Select", "Select Word", "Select to Line Start",
                       "Select to Line End", "Select Page Up/Down",
                       "Select to Start/End", "Delete Word Left", "Delete Word Right",
                       "Delete to Line End", "Delete to Line Start", "Indent", "Outdent",
                       "Yank line up to cursor", "Yank line after cursor",
                       "Insert currently yanked text", "Insert assignment operator",
                       "Insert pipe operator", "Show help for function at cursor",
                       "Show source code for function at cursor",
                       "Find usages for symbol at cursor (C++)", "Attempt completion",
                       "Navigate candidates", "Accept selected candidate",
                       "Dismiss completion popup", "Move focus to Source Editor",
                       "Move focus to Console", "Move focus to Help", "Show History",
                       "Show Files", "Show Plots", "Show Packages", "Show Environment",
                       "Show Git/SVN", "Show Build", "Sync Editor & PDF Preview",
                       "Show Keyboard Shortcut Reference", "Build and Reload",
                       "Load All (devtools)", "Test Package (Desktop)",
                       "Test Package (Web)", "Check Package", "Document Package",
                       "Toggle Breakpoint", "Execute Next Line", "Step Into Function",
                       "Finish Function/Loop", "Continue", "Stop Debugging",
                       "Previous plot", "Next plot", "Diff active source document",
                       "Commit changes", "Scroll diff view", "Stage/Unstage (Git)",
                       "Stage/Unstage and move to next (Git)",
                       "Quit Session (desktop only)", "Restart R Session"),
   Description_esp = c("Mueve el cursor a la consola", "Limpia consola",
                       "Mueve el cursor al comienzo de la línea",
                       "Mueve el cursor al final de la línea",
                       "Navegar por el historial de comandos", "Historial de comandos emergentes",
                       "Interrumpir el comando actualmente en ejecución",
                       "Cambiar directorio de trabajo", "Ir a archivo / función",
                       "Mover el cursor al Source Editor",
                       "Nuevo documento (excepto en Chrome / Windows)", "Nuevo documento (solo Chrome)",
                       "Abrir documento", "Guardar documento activo",
                       "Cerrar documento activo (excepto en Chrome)",
                       "Cerrar documento activo (solo Chrome)", "Cerrar todos los documentos abiertos",
                       "Vista previa de HTML (Markdown y HTML)", "Knit documento (knitr)",
                       "Compilar Notebook", "Compilar PDF (TeX y Sweave)",
                       "Insertar chunk (Sweave and Knitr)", "Insertar sección de código",
                       "Ejecutar línea / selección actual",
                       "Ejecutar la línea / selección actual (conservar la posición del cursor)",
                       "Vuelva a ejecutar la región anterior",
                       "Ejecutar documento actual",
                       "Ejecutar desde el documento que comienza hasta la línea actual",
                       "Ejecutar desde la línea actual hasta el final del documento",
                       "Ejecuta la definición de la función actual", "Ejecute la sección de código actual",
                       "Ejecute el código anterior de Sweave / Rmd",
                       "Ejecute el chunk de Sweave / Rmd actual",
                       "Ejecute el siguiente chunk Sweave / Rmd", "Source un archivo", "Source al documento actual",
                       "Souce al documento actual (con echo)", "Fold a la selección",
                       "Des-\"fold\" a la selección", "Fold a todo",
                       "Des-\"fold\" a todo", "Ir a la linea", "Saltar a",
                       "Cambiar a pestaña de ambiente", "Pestaña anterior", "Pestaña siguiente",
                       "Primera pestaña", "Última pestaña", "Navegar hacia atrás",
                       "Navegar hacia adelante",
                       "Extraer la función de la selección", "Extraer variable de selección",
                       "Re-alinear líneas del código",
                       "Comentar / descomentar línea actual / selección", "Refluir comentario", "Reformatear selección",
                       "Mostrar diagnósticos", "Transponer letras",
                       "Mover líneas arriba / abajo", "Copiar líneas arriba / abajo",
                       "Saltar a Matching Brace / Paren", "Expandir a Matching Brace / Paren",
                       "Seleccionar a Matching Brace / Paren",
                       "Añadir cursor sobre el cursor actual",
                       "Añadir cursor debajo del cursor actual", "Mover el cursor activo hacia arriba",
                       "Mover el cursor activo hacia abajo", "Encontrar y reemplazar",
                       "Encontrar siguiente", "Encontrar anterior",
                       "Usar selección para buscar", "Reemplazar y buscar", "Buscar en archivos",
                       "Revisar ortografía", "Deshacer", "Rehacer", "Cortar",
                       "Copiar", "Pegar", "Seleccionar todo", "Saltar a la palabra",
                       "Saltar al inicio / fin", "Eliminar línea", "Seleccionar",
                       "Seleccionar palabra",
                       "Seleccionar hasta inicio de línea", "Seleccionar hasta final de línea",
                       "Seleccionar página arriba / abajo", "Seleccionar para comenzar / finalizar",
                       "Eliminar palabra izquierda", "Eliminar Word Right",
                       "Eliminar al final de línea", "Eliminar al inicio de línea",
                       "Sangría", "Outdent",
                       "Eliminar línea desde la izquierda hasta el cursor",
                       "Eliminar línea desde la derecha hasta el cursor", "Insertar texto actualmente arrancado",
                       "Insertar operador de asignación", "Insertar pipe",
                       "Mostrar ayuda para la función en el cursor",
                       "Mostrar el código fuente de la función en el cursor",
                       "Encuentra usos para el símbolo en el cursor (C ++)", "Autocompletar", "Navegar códigos",
                       "Aceptar candidato seleccionado",
                       "Cancelar ventana emergente de autocompletar", "Mover el foco al Source Edition",
                       "Mover el foco a la consola", "Mover el foco a Ayuda",
                       "Mostrar historia", "Mostrar archivos", "Mostrar gráficos",
                       "Mostrar paquetes", "Mostrar entorno",
                       "Mostrar Git / SVN", "Mostrar compilación",
                       "Editor de sincronización y vista previa de PDF",
                       "Mostrar referencia de acceso directo de teclado", "Construir y recargar",
                       "Cargar todo (devtools)", "Paquete Test (escritorio)", "Paquete Test (web)",
                       "Comprobar paquete", "Paquete de documentos",
                       "Punto de interrupción de palanca", "Ejecutar línea siguiente",
                       "Paso a la función", "Función de acabado / bucle", "Seguir",
                       "Dejar de depurar", "Gráfico anterior", "Siguiente Gráfico",
                       "Diferenciar documento fuente activo", "Cometer cambios",
                       "Desplazar vista de diferencia", "Stage / Unstage (Git)",
                       "Stage / Unstage y pasar al siguiente (Git)",
                       "Salir de sesión (solo escritorio)", "Reiniciar sesión R"),
     Windows_Linux = c("Ctrl+2", "Ctrl+L", "Home", "End", "Up/Down", "Ctrl+Up",
                       "Esc", "Ctrl+Shift+H", "Ctrl+.", "Ctrl+1",
                       "Ctrl+Shift+N", "Ctrl+Alt+Shift+N", "Ctrl+O", "Ctrl+S", "Ctrl+W",
                       "Ctrl+Alt+W", "Ctrl+Shift+W", "Ctrl+Shift+K", "Ctrl+Shift+K",
                       "Ctrl+Shift+K", "Ctrl+Shift+K", "Ctrl+Alt+I",
                       "Ctrl+Shift+R", "Ctrl+Enter", "Alt+Enter", "Ctrl+Shift+P",
                       "Ctrl+Alt+R", "Ctrl+Alt+B", "Ctrl+Alt+E", "Ctrl+Alt+F", "Ctrl+Alt+T",
                       "Ctrl+Alt+P", "Ctrl+Alt+C", "Ctrl+Alt+N", "Ctrl+Shift+O",
                       "Ctrl+Shift+S", "Ctrl+Shift+Enter", "Alt+L",
                       "Shift+Alt+L", "Alt+O", "Shift+Alt+O", "Shift+Alt+G", "Shift+Alt+J",
                       "Ctrl+Shift+.", "Ctrl+F11", "Ctrl+F12", "Ctrl+Shift+F11",
                       "Ctrl+Shift+F12", "Ctrl+F9", "Ctrl+F10", "Ctrl+Alt+X",
                       "Ctrl+Alt+V", "Ctrl+I", "Ctrl+Shift+C", "Ctrl+Shift+/",
                       "Ctrl+Shift+A", "Ctrl+Shift+Alt+P", NA, "Alt+Up/Down",
                       "Shift+Alt+Up/Down", "Ctrl+P", "Ctrl+Shift+E", "Ctrl+Shift+Alt+E",
                       "Ctrl+Alt+Up", "Ctrl+Alt+Down", "Ctrl+Alt+Shift+Up",
                       "Ctrl+Alt+Shift+Down", "Ctrl+F", "Win: F3, Linux: Ctrl+G",
                       "Win: Shift+F3, Linux: Ctrl+Shift+G", "Ctrl+F3",
                       "Ctrl+Shift+J", "Ctrl+Shift+F", "F7", "Ctrl+Z", "Ctrl+Shift+Z",
                       "Ctrl+X", "Ctrl+C", "Ctrl+V", "Ctrl+A", "Ctrl+Left/Right",
                       "Ctrl+Home/End or Ctrl+Up/Down", "Ctrl+D", "Shift+[Arrow]",
                       "Ctrl+Shift+Left/Right", "Alt+Shift+Left", "Alt+Shift+Right",
                       "Shift+PageUp/PageDown",
                       "Ctrl+Shift+Home/End or Shift+Alt+Up/Down", "Ctrl+Backspace", NA, NA, NA,
                       "Tab (at beginning of line)", "Shift+Tab", "Ctrl+U", "Ctrl+K", "Ctrl+Y",
                       "Alt+-", "Ctrl+Shift+M", "F1", "F2", "Ctrl+Alt+U",
                       "Tab or Ctrl+Space", "Up/Down", "Enter, Tab, or Right", "Esc",
                       "Ctrl+1", "Ctrl+2", "Ctrl+3", "Ctrl+4", "Ctrl+5", "Ctrl+6",
                       "Ctrl+7", "Ctrl+8", "Ctrl+9", "Ctrl+0", "Ctrl+F8",
                       "Alt+Shift+K", "Ctrl+Shift+B", "Ctrl+Shift+L", "Ctrl+Shift+T",
                       "Ctrl+Alt+F7", "Ctrl+Shift+E", "Ctrl+Shift+D", "Shift+F9",
                       "F10", "Shift+F4", "Shift+F6", "Shift+F5", "Shift+F8",
                       "Ctrl+Alt+F11", "Ctrl+Alt+F12", "Ctrl+Alt+D", "Ctrl+Alt+M",
                       "Ctrl+Up/Down", "Spacebar", "Enter", "Ctrl+Q",
                       "Ctrl+Shift+F10"),
               Mac = c("Ctrl+2", "Ctrl+L", "Command+Left", "Command+Right",
                       "Up/Down", "Command+Up", "Esc", "Ctrl+Shift+H",
                       "Ctrl+.", "Ctrl+1", "Command+Shift+N", "Command+Shift+Alt+N",
                       "Command+O", "Command+S", "Command+W", "Command+Option+W",
                       "Command+Shift+W", "Command+Shift+K", "Command+Shift+K",
                       "Command+Shift+K", "Command+Shift+K", "Command+Option+I",
                       "Command+Shift+R", "Command+Enter", "Option+Enter",
                       "Command+Shift+P", "Command+Option+R", "Command+Option+B",
                       "Command+Option+E", "Command+Option+F", "Command+Option+T",
                       "Command+Option+P", "Command+Option+C", "Command+Option+N",
                       "Command+Shift+O", "Command+Shift+S", "Command+Shift+Enter",
                       "Cmd+Option+L", "Cmd+Shift+Option+L", "Cmd+Option+O",
                       "Cmd+Shift+Option+O", "Cmd+Shift+Option+G",
                       "Cmd+Shift+Option+J", "Ctrl+Shift+.", "Ctrl+F11", "Ctrl+F12",
                       "Ctrl+Shift+F11", "Ctrl+Shift+F12", "Cmd+F9", "Cmd+F10",
                       "Command+Option+X", "Command+Option+V", "Command+I", "Command+Shift+C",
                       "Command+Shift+/", "Command+Shift+A", "Command+Shift+Alt+P",
                       "Ctrl+T", "Option+Up/Down", "Command+Option+Up/Down",
                       "Ctrl+P", "Ctrl+Shift+E", "Ctrl+Shift+Alt+E", "Ctrl+Alt+Up",
                       "Ctrl+Alt+Down", "Ctrl+Alt+Shift+Up",
                       "Ctrl+Alt+Shift+Down", "Command+F", "Command+G", "Command+Shift+G",
                       "Command+E", "Command+Shift+J", "Command+Shift+F", "F7", "Command+Z",
                       "Command+Shift+Z", "Command+X", "Command+C", "Command+V",
                       "Command+A", "Option+Left/Right",
                       "Command+Home/End or Command+Up/Down", "Command+D", "Shift+[Arrow]",
                       "Option+Shift+Left/Right", "Command+Shift+Left",
                       "Command+Shift+Right", "Shift+PageUp/Down", "Command+Shift+Up/Down",
                       "Option+Backspace or Ctrl+Option+Backspace", "Option+Delete",
                       "Ctrl+K", "Option+Backspace", "Tab (at beginning of line)",
                       "Shift+Tab", "Ctrl+U", "Ctrl+K", "Ctrl+Y", "Option+-",
                       "Cmd+Shift+M", "F1", "F2", "Cmd+Option+U",
                       "Tab or Command+Space", "Up/Down", "Enter, Tab, or Right", "Esc", "Ctrl+1",
                       "Ctrl+2", "Ctrl+3", "Ctrl+4", "Ctrl+5", "Ctrl+6", "Ctrl+7",
                       "Ctrl+8", "Ctrl+9", "Ctrl+0", "Cmd+F8", "Option+Shift+K",
                       "Cmd+Shift+B", "Cmd+Shift+L", "Cmd+Shift+T", "Cmd+Alt+F7",
                       "Cmd+Shift+E", "Cmd+Shift+D", "Shift+F9", "F10",
                       "Shift+F4", "Shift+F6", "Shift+F5", "Shift+F8",
                       "Command+Option+F11", "Command+Option+F12", "Ctrl+Option+D", "Ctrl+Option+M",
                       "Ctrl+Up/Down", "Spacebar", "Enter", "Command+Q",
                       "Command+Shift+F10"),
           Seccion = c("Console", "Console", "Console", "Console", "Console",
                       "Console", "Console", "Console", "Source", "Source",
                       "Source", "Source", "Source", "Source", "Source", "Source",
                       "Source", "Source", "Source", "Source", "Source", "Source",
                       "Source", "Source", "Source", "Source", "Source",
                       "Source", "Source", "Source", "Source", "Source", "Source",
                       "Source", "Source", "Source", "Source", "Source", "Source",
                       "Source", "Source", "Source", "Source", "Source", "Source",
                       "Source", "Source", "Source", "Source", "Source", "Source",
                       "Source", "Source", "Source", "Source", "Source",
                       "Source", "Source", "Source", "Source", "Source", "Source",
                       "Source", "Source", "Source", "Source", "Source", "Source",
                       "Source", "Source", "Source", "Source", "Source", "Source",
                       "Editing (Console and Source)",
                       "Editing (Console and Source)", "Editing (Console and Source)",
                       "Editing (Console and Source)", "Editing (Console and Source)",
                       "Editing (Console and Source)", "Editing (Console and Source)",
                       "Editing (Console and Source)", "Editing (Console and Source)",
                       "Editing (Console and Source)",
                       "Editing (Console and Source)", "Editing (Console and Source)",
                       "Editing (Console and Source)", "Editing (Console and Source)",
                       "Editing (Console and Source)", "Editing (Console and Source)",
                       "Editing (Console and Source)", "Editing (Console and Source)",
                       "Editing (Console and Source)", "Editing (Console and Source)",
                       "Editing (Console and Source)",
                       "Editing (Console and Source)", "Editing (Console and Source)",
                       "Editing (Console and Source)", "Editing (Console and Source)",
                       "Editing (Console and Source)", "Editing (Console and Source)",
                       "Editing (Console and Source)", "Editing (Console and Source)",
                       "Completions (Console and Source)",
                       "Completions (Console and Source)", "Completions (Console and Source)",
                       "Completions (Console and Source)", "Views", "Views", "Views",
                       "Views", "Views", "Views", "Views", "Views", "Views", "Views",
                       "Views", "Views", "Build", "Build", "Build", "Build",
                       "Build", "Build", "Debug", "Debug", "Debug", "Debug",
                       "Debug", "Debug", "Plots", "Plots", "Git/SVN", "Git/SVN",
                       "Git/SVN", "Git/SVN", "Git/SVN", "Session", "Session")
)



base_tuit <- base_atajo %>%
  sample_n(., 1)

descripcion <- paste(base_tuit$Description_esp, paste0("[", base_tuit$Description_eng, "]"), sep = "")
comando_win_lin <- base_tuit$Windows_Linux
comando_mac <- base_tuit$Mac
referencia <- base_tuit$Seccion

twit <- glue::glue('  \n Atajo en R[R Shortcut]: {descripcion} \n ',
                   " \n \n",
                   '  \n Sección de Rstudio[Rstudio section]: {referencia} \n ',
                   " \n \n",
                   'Windows | Linux: {comando_win_lin} \n ',
                   " \n \n",
                   'Mac: {comando_mac}')

# twit <- glue::glue('  \n Atajo en R[R Shortcut]: {descripcion} \n ',
#                    " \n \n",
#                    'Windows | Linux: {comando_win_lin} \n ',
#                    " \n \n",
#                    'Mac: {comando_mac}')

if(nchar(twit) <= 280) tweet(twit)
